steps:
- name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/mypocket-web',
    '-f', 'MyPocket.Web/Dockerfile',
    'MyPocket.Web'
  ]
  id: Build

- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/$PROJECT_ID/mypocket-web']
  id: Push

- name: gcr.io/google.com/cloudsdk/cloud-sdk
  args: ['run', 'deploy', 'mypocket-cd', '--image', 'gcr.io/$PROJECT_ID/mypocket-web', '--region', 'asia-east1']
  id: Deploy
